# 基础配置
pos_data:
  tbl_sales_fp: "abfss://datalake-dic@pdisajedidls002.dfs.core.windows.net/Gold/TBL_SALES_DETAILS/"
  query_period: 1
  campaign_start_date: "20241211"
  comp_cd: "3618"  #九州
  
#
node_relation:
  node_json_fp: '/Volumes/develop/cdp/node/'
  relation_json_fp: '/Volumes/develop/cdp/relation/'

# 日志配置
logging:
  level: "INFO"
  file: "app.log"